main:
  - name: Modules
    identifier: modules
    weight: 9
    params:
      icon:
        name: boxes
        vendor: bs
        className: 'text-primary'

  - name: Projects
    identifier: projects
    weight: 10
    params:
      icon:
        name: boxes
        vendor: bs
        color: '#712cf9'

  - name: HB Framework
    parent: projects
    url: https://hb.hugomods.com/
    params:
      icon:
        name: hugo
        vendor: simple
        color: '#712cf9'
