hb:
  header:
    # logo_bg: '#fff'
    socials:
      github: hugomods
      paypal: razonyang
      kofi: razonyang
  footer:
    socials:
      github: hugomods
      paypal: razonyang
      kofi: razonyang
  blog:
    home:
      recent_posts: 12

seo:
  favicons:
    icon: images/logo.png

pwa:
  icon_path: images/logo.png
  # debug: true

hugopress:
  modules:
    custom:
      hooks:
        hb-docs-doc-content-begin:
          cacheable: true
