hb:
  header:
    logo_bg: '#fff'
    socials:
      github: hugomods
      paypal: razonyang
      kofi: razonyang
  footer:
    socials:
      github: hugomods
      paypal: razonyang
      kofi: razonyang

seo:
  favicons:
    icon: images/logo.png

pwa:
  icon_path: images/logo.png
  debug: true