main:
  - name: 图标
    identifier: icons
    weight: 10
    url: https://icons.hugomods.com/
    params:
      icon:
        name: icons
        vendor: fas

  - name: HB 框架
    weight: 20
    url: https://hbstack.dev/
    params:
      icon:
        name: hugo
        vendor: simple
