name: site-pwa

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'
      - 'pwa/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: pwa
    secrets: inherit
