name: site-echarts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-echarts.yaml'
      - 'common/**'
      - 'echarts/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: echarts
    secrets: inherit
