name: site-base

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-base.yaml'
      - 'common/**'
      - 'base/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: base
    secrets: inherit
