name: site-docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-docker.yaml'
      - 'common/**'
      - 'docker/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: docker
    secrets: inherit
