name: site-decap-cms

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-decap-cms.yaml'
      - 'common/**'
      - 'decap-cms/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: decap-cms
    secrets: inherit
