name: site-icons

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-icons.yaml'
      - 'common/**'
      - 'icons/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: icons
    secrets: inherit
