name: site-blog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-blog.yaml'
      - 'common/**'
      - 'blog/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: blog
    secrets: inherit
