name: site-kroki

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-kroki.yaml'
      - 'common/**'
      - 'kroki/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: kroki
    secrets: inherit
