name: site-decap-cms

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'
      - 'decap-cms/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: decap-cms
    secrets: inherit
