name: site-home

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-home.yaml'
      - 'common/**'
      - 'home/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: home
    secrets: inherit
