name: site-icons

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'
      - 'icons/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: icons
    secrets: inherit
