name: site-pwa

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-pwa.yaml'
      - 'common/**'
      - 'pwa/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: pwa
    secrets: inherit
