name: site-search

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-search.yaml'
      - 'common/**'
      - 'search/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: search
    secrets: inherit
