name: site-echarts

on:
  workflow_dispatch:
  push:
    branches:
      - kroki
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-kroki.yaml'
      - 'common/**'
      - 'kroki/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: kroki
    secrets: inherit
