name: site-base

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'
      - 'base/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: base
    secrets: inherit
