name: site-images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-images.yaml'
      - 'common/**'
      - 'images/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: images
    secrets: inherit
