name: site-search

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'
      - 'search/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: search
    secrets: inherit
