name: site-shortcodes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-shortcodes.yaml'
      - 'common/**'
      - 'shortcodes/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: shortcodes
    secrets: inherit
