name: site-hugopress

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-hugopress.yaml'
      - 'common/**'
      - 'hugopress/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: hugopress
    secrets: inherit
