name: site-seo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/site.yaml'
      - '.github/workflows/site-seo.yaml'
      - 'common/**'
      - 'seo/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: seo
    secrets: inherit
