name: site-echarts

on:
  push:
    branches:
      - kroki
    paths:
      - 'common/**'
      - 'kroki/**'

jobs:
  version-matrix:
    uses: ./.github/workflows/site.yaml
    with:
      name: kroki
    secrets: inherit
